### ISSUE TITLE
Research plan 

### ISSUE THREAD

**Issue by Kanyinsola70** [zuri-training/Chunk-file-team-45#26]
Contains iOTA  research background, problem statement, research questions, interview qustions, method of recruitment, screener questions that was conducted by all the product designers in team 45

https://docs.google.com/document/d/1Kg80WJVM2ufSrR5N105s9h-7nLH0aASdJzOLd7cXe6M/edit

**Comment by Kanyinsola70** [comment]
DONE

**Comment by Uch1haa** [comment]
Carried out interview questions on developers

**Comment by adeosunk** [comment]
Done as well.

**Comment by Gozie-web** [comment]
carried out interview on schools, specifically those working in administrative office.
