### ISSUE TITLE
User Research 

### ISSUE THREAD

**Issue by Kanyinsola70** [zuri-training/Chunk-file-team-45#27]
Using the interview questions that was drafted by product designer, we interviewed 3 types of users, ecommercce, adminstrative assistant and developers.

**Comment by Kanyinsola70** [comment]
Done

**Comment by Kanyinsola70** [comment]
Done

**Comment by FaVe-N** [comment]
Done

**Comment by ireneighalo** [comment]
Done

**Comment by chigojude** [comment]
This has been completed and incorporated

**Comment by Abbiechan1234** [comment]
This issue has been completed

**Comment by adeosunk** [comment]
Done.

**Comment by PGVD** [comment]
The issue has be resolved.

**Comment by Uch1haa** [comment]
The issue has been resolved

**Comment by EchoBills** [comment]
Done

**Comment by Omowunmimi** [comment]
Done

**Comment by Abbiechan1234** [comment]
Ok

**Comment by Gozie-web** [comment]
The have been resolved successfully.

**Comment by ireneighalo** [comment]
This has been resolved
