### ISSUE TITLE
Contact us/FAQs design

### ISSUE THREAD

**Issue by chigojude** [zuri-training/Chunk-file-team-45#54]
Hi Uloma and Lazarus, this task us to design the pages mentioned above in responsiveness to mobile and tablet as well as the Web platform.

**Comment by FaVe-N** [comment]
The pages have been designed and responsiveness was ensured as well.

**Comment by EchoBills** [comment]
> Hi Uloma and Lazarus, this task us to design the pages mentioned above in responsiveness to mobile and tablet as well as the Web platform.

It has been designed and submitted.

**Comment by EchoBills** [comment]
issue has been resolved
