### ISSUE TITLE
Dashboard  - design and responsiveness 

### ISSUE THREAD

**Issue by chigojude** [zuri-training/Chunk-file-team-45#55]

**Comment by chigojude** [comment]
![Dashboard mobile HI-FI](https://user-images.githubusercontent.com/32585188/183448248-1f90d354-f0e0-4a14-ab26-c49ee8f67591.png)

These tasks have been resolved and here are snapshots of the final output (3 screens - screen 1 for web, screens 2 & 3 of tablet and mobile sizes to show responsiveness)

**Comment by chigojude** [comment]
![Dashboard WEB HI-FI](https://user-images.githubusercontent.com/32585188/183448725-c24adf9c-02b7-4ac4-8ddd-aaa682f4d6c3.png)
Web screen

**Comment by chigojude** [comment]
![Dashboard tablet HIFI](https://user-images.githubusercontent.com/32585188/183448788-29d98b0a-973c-40c3-bd67-941b90114d06.png)

Tablet screen

**Comment by Kanyinsola70** [comment]
DONE
