### ISSUE TITLE
Style guide components

### ISSUE THREAD

**Issue by Kanyinsola70** [zuri-training/Chunk-file-team-45#72]

**Comment by Gozie-web** [comment]
https://www.figma.com/file/u1asikejW1s1pF9NU51pPd/FIGMA-(chunk-file)--PROJECT-TEAM-45?node-id=264%3A2121

**Comment by Abbiechan1234** [comment]
is this issue resolved 
can it be closed

**Comment by Omowunmimi** [comment]
Resolved
