### ISSUE TITLE
Share and download pages

### ISSUE THREAD

**Issue by Gozie-web** [zuri-training/Chunk-file-team-45#78]
https://www.figma.com/file/R0PgiAq3jAWxXKuYN8w8FZ/COPY-FIGMA-(chunk-file)--PROJECT-TEAM-45?node-id=2453%3A10007
The share and download pages are modals.
The low fidelity (lo-fi) of the pages where designed by me.

**Comment by omotayobee** [comment]
https://www.figma.com/file/R0PgiAq3jAWxXKuYN8w8FZ/COPY-FIGMA-(chunk-file)--PROJECT-TEAM-45?node-id=2453%3A10007

High fidelity page assigned by me.
